#spring.application.name=api-gateway
#server.port=8085
#
## Không yêu c?u token - dùng ?? login, ??ng ký
#spring.cloud.gateway.routes[0].id=user-service
#spring.cloud.gateway.routes[0].uri=http://localhost:8083
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**
#
## Có yêu c?u token - submit bài thi
#spring.cloud.gateway.routes[1].id=submit-service
#spring.cloud.gateway.routes[1].uri=http://localhost:8081
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/submissions/**
#spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter
#
## CORS
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:5173
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
#
## JWT secret (gi?ng bên UserService)
#jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/auth/**
        - id: judge-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/judge/**
        - id: probleam-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/probleam/**
        - id: submit-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/submissions/**
          filters:
            - AuthenticationFilter
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
